# Generated by Django 5.1.2 on 2024-10-14 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0003_budget'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='rem_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
