# Generated by Django 5.1.2 on 2024-10-14 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
