# Generated by Django 5.1.2 on 2024-10-14 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0004_alter_budget_rem_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='time_period',
            field=models.CharField(choices=[('Week', 'Week'), ('Month', 'Month'), ('Year', 'Year')], default=1, max_length=200),
        ),
    ]
